name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qado-rml-applicator:latest
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag qado-rml-applicator:latest bigoli98/qado-rml-applicator:latest
    - name: Tag fixed version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag qado-rml-applicator:latest "bigoli98/qado-rml-applicator:${{ github.ref_name }}"
    - name: Push latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push bigoli98/qado-rml-applicator:latest
    - name: Push fixed docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push "bigoli98/qado-rml-applicator:${{ github.ref_name }}"
    - name: Init update
      if: startsWith(github.ref, 'refs/tags/')
      uses: MindMaster98/docker-service-updater@v0.1.5
      with:
        updater_host: ${{ secrets.UPDATER_HOST }}
        api_key: ${{ secrets.API_KEY }}